<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.*" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\Core\ROCA.Emuna360.Application\ROCA.Emuna360.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\ROCA.Emuna360.Infrastructure\ROCA.Emuna360.Infrastructure.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Components\Pages\Registry\" />
  </ItemGroup>
</Project>